{{-- The AI reading of one document, as a full-width row under it.

     A separate <tr> rather than a wider cell, because a contract summary needs the room —
     and because the collapse has to sit inside a <td> to keep the table markup valid; a
     <div> dropped straight into <tbody> is hoisted out by the browser.

     Rendered only when there is something to show. A document that could not be read says
     so on its own row (_ai-chip) instead, rather than opening onto an empty panel.

     Expects: $doc, $span (colspan), $vendor, $canManage. --}}
@if($doc->file_path && $doc->hasAiSummary())
@php
    $vndIsContract = $doc instanceof \App\Models\VendorContract;
    $vndAiId = 'vndAiSum'.($vndIsContract ? 'c' : 'b').$doc->id;
@endphp
<tr class="vnd-ai-row">
    <td colspan="{{ $span }}" class="p-0 border-0">
        <div class="collapse" id="{{ $vndAiId }}">
            <div class="vnd-ai-panel {{ $doc->ai_status === 'ok' ? '' : 'vnd-ai-panel-warn' }}">

                {{-- A partial transcription is announced here as well as in the answers that
                     rely on it: this panel is where somebody decides they have read enough. --}}
                @if($doc->ai_status !== 'ok' && $doc->aiNote())
                    <div class="vnd-ai-note"><i class="bi bi-exclamation-triangle me-1"></i>{{ $doc->aiNote() }}</div>
                @endif

                @if($doc->ai_summary)
                    <div class="vnd-ai-md">{!! $doc->aiSummaryHtml() !!}</div>
                @endif

                @if($doc->ai_key_points)
                    <ul class="vnd-ai-points">
                        @foreach($doc->ai_key_points as $vndPoint)
                            <li>{{ $vndPoint }}</li>
                        @endforeach
                    </ul>
                @endif

                <div class="vnd-ai-foot">
                    @php
                        // Built in PHP, never as "document@if(...)": Blade only treats @ as a
                        // directive when it is NOT preceded by a word character, so one glued
                        // to the end of a word compiles through as literal text and leaves the
                        // matching @endif unbalanced — a ViewException at render, not compile.
                        //
                        // summaryProvenance() rather than a fixed "Generated by AI" line: the
                        // summary is editable now, and printing a machine's name over wording
                        // a person typed is how a correction gets dismissed as a guess.
                        $vndAiStamp = $doc->summaryProvenance();
                    @endphp
                    <span>
                        <i class="bi bi-{{ $doc->summaryIsEdited() ? 'pencil-square' : 'robot' }} me-1"></i>{{ $vndAiStamp }}
                        Check it against the document before acting on it.
                    </span>

                    {{-- Neither Re-read nor Ask AI is repeated here. Both live in the row's
                         Actions column — which is also where a document that failed to read,
                         and so has no panel at all, has to be able to reach them. One home,
                         not two. --}}
                </div>
            </div>
        </div>
    </td>
</tr>
@endif
