{{-- The AI reading of one document, as a full-width row under it.

     A separate <tr> rather than a wider cell, because a contract summary needs the room —
     and because the collapse has to sit inside a <td> to keep the table markup valid; a
     <div> dropped straight into <tbody> is hoisted out by the browser.

     Rendered only when there is something to show. A document that could not be read says
     so on its own row (_ai-chip) instead, rather than opening onto an empty panel.

     Expects: $doc, $span (colspan), $vendor, $canManage. --}}
@if($doc->file_path && $doc->hasAiSummary())
@php
    $vndIsContract = $doc instanceof \App\Models\VendorContract;
    $vndAiId = 'vndAiSum'.($vndIsContract ? 'c' : 'b').$doc->id;
    // The link keeps the operator on the tab they are reading and opens the assistant OVER
    // it: `ask` opens the panel, `focus` says which document to tick. Deliberately not
    // tab=ask — that names no tab any more, so it would bounce them back to Profile and
    // away from the very row they just asked about.
    $vndAskTab = $vndIsContract ? 'contracts' : 'billing';
@endphp
<tr class="vnd-ai-row">
    <td colspan="{{ $span }}" class="p-0 border-0">
        <div class="collapse" id="{{ $vndAiId }}">
            <div class="vnd-ai-panel {{ $doc->ai_status === 'ok' ? '' : 'vnd-ai-panel-warn' }}">

                {{-- A partial transcription is announced here as well as in the answers that
                     rely on it: this panel is where somebody decides they have read enough. --}}
                @if($doc->ai_status !== 'ok' && $doc->aiNote())
                    <div class="vnd-ai-note"><i class="bi bi-exclamation-triangle me-1"></i>{{ $doc->aiNote() }}</div>
                @endif

                @if($doc->ai_summary)
                    <div class="vnd-ai-md">{!! $doc->aiSummaryHtml() !!}</div>
                @endif

                @if($doc->ai_key_points)
                    <ul class="vnd-ai-points">
                        @foreach($doc->ai_key_points as $vndPoint)
                            <li>{{ $vndPoint }}</li>
                        @endforeach
                    </ul>
                @endif

                <div class="vnd-ai-foot">
                    @php
                        // Built in PHP, never as "document@if(...)": Blade only treats @ as a
                        // directive when it is NOT preceded by a word character, so one glued
                        // to the end of a word compiles through as literal text and leaves the
                        // matching @endif unbalanced — a ViewException at render, not compile.
                        $vndAiStamp = 'Generated by AI from the uploaded document'
                            .($doc->ai_at ? ' on '.fmt_datetime($doc->ai_at) : '').'.';
                    @endphp
                    <span>
                        <i class="bi bi-robot me-1"></i>{{ $vndAiStamp }}
                        Check it against the document before acting on it.
                    </span>

                    {{-- Re-summarise is NOT repeated here: it lives in the row's Actions
                         column, which is where a document that failed to read — and so has
                         no panel at all — has to be able to reach it. One home, not two. --}}
                    <span class="vnd-ai-actions">
                        @if($doc->hasAiText())
                            <a class="vnd-ai-ask" href="{{ route('vendors.show', [$vendor, 'tab' => $vndAskTab, 'ask' => 1, 'focus' => $doc->askKey()]) }}">
                                <i class="bi bi-chat-dots me-1"></i>Ask about this document
                            </a>
                        @endif
                    </span>
                </div>
            </div>
        </div>
    </td>
</tr>
@endif
