<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * WHO the document is between, and whether a human has since rewritten what the AI said
 * about it.
 *
 * `companies_involved` is the parties named in the document itself — read off the file by
 * the scan, never picked from our own company list. It is deliberately free text rather
 * than a FK: a contract regularly names a legal entity we do not carry a row for (the
 * vendor's own holding company, a sister company being supplied, a party that has since
 * been renamed), and refusing to record a party because we have no id for it would put the
 * one fact this column exists for into `notes`, where nothing can read it.
 *
 * `ai_summary_edited_at` / `_by` exist because the summary is now EDITABLE. Without them
 * the row's footer would keep claiming "Generated by AI from the uploaded document" over
 * wording a person typed — the summary is the column the whole listing is now read from,
 * so who last stood behind it has to be recoverable. They also let the Re-read confirmation
 * warn that a human edit is about to be thrown away.
 */
return new class extends Migration
{
    /** vendor_contracts and vendor_billing_documents take the identical block. */
    private const TABLES = ['vendor_contracts', 'vendor_billing_documents'];

    public function up(): void
    {
        foreach (self::TABLES as $table) {
            Schema::table($table, function (Blueprint $t) {
                $t->json('companies_involved')->nullable()->after('ai_at');
                $t->timestamp('ai_summary_edited_at')->nullable()->after('companies_involved');
                $t->foreignId('ai_summary_edited_by')->nullable()->after('ai_summary_edited_at')
                    ->constrained('users')->nullOnDelete();
            });
        }
    }

    public function down(): void
    {
        foreach (self::TABLES as $table) {
            Schema::table($table, function (Blueprint $t) {
                // Explicit, because dropping a column under a foreign key leaves the
                // constraint orphaned on MySQL and the next migration run fails on it.
                $t->dropConstrainedForeignId('ai_summary_edited_by');
                $t->dropColumn(['companies_involved', 'ai_summary_edited_at']);
            });
        }
    }
};
