<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A document that has been uploaded and READ, but not yet filed.
 *
 * The Add-Document flow now shows the operator the AI's summary and lets them correct it
 * BEFORE the contract or billing row exists. Something has to hold the uploaded file and
 * the reading between those two requests, and it cannot be the destination row: a scan the
 * operator abandons would leave a half-filed contract on the vendor profile that nobody
 * asked for and that reads exactly like a real one.
 *
 * `token` is generated by the browser and sent WITH the upload, so the staging row is
 * created before the model is called and can therefore be found again by a client that
 * lost the response. That is not a nicety — the read runs inside the request, and a long
 * PDF can outlive the edge timeout on live while PHP happily finishes and writes the row
 * here. Without the token the work would be done, paid for, and unreachable.
 *
 * Rows are consumed on save (deleted, file kept) and swept by `vendors:prune-document-scans`
 * otherwise — a surviving row always means an unclaimed file, which is what makes deleting
 * the file with it safe.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('vendor_document_scans', function (Blueprint $table) {
            $table->id();
            $table->foreignId('vendor_id')->constrained('vendors')->cascadeOnDelete();
            // Who uploaded it. The save path checks this: a staging row is one operator's
            // unfinished work, and a token is guessable enough that it should not be a
            // second person's way into a file they never uploaded.
            $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();

            $table->string('token', 64)->unique();
            // 'contract' | 'billing' — which table this is destined for. Checked on save so
            // a contract scan cannot be filed as an invoice, which would put a contract's
            // extracted term into a billing document's due date.
            $table->string('kind', 20);

            $table->string('file_path');
            $table->string('original_filename')->nullable();

            // Mirrors the ai_status vocabulary on the destination row (pending | ok |
            // partial | empty | skipped | disabled | failed) so the modal, the row and the
            // assistant all describe one document's state the same way.
            $table->string('status', 20)->default('pending');
            $table->longText('summary')->nullable();
            $table->json('key_points')->nullable();
            $table->longText('text')->nullable();
            $table->json('companies')->nullable();
            // Everything the scan read that used to be typed by hand — dates, numbers,
            // figures. Carried as JSON rather than as columns mirroring both destination
            // tables: this row is a courier, not a second register.
            $table->json('fields')->nullable();

            $table->timestamps();

            $table->index(['vendor_id', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('vendor_document_scans');
    }
};
