{{--
    One attachment inside a claim row of the printable report.

    Three outcomes, in order of preference:
      1. An image upload  -> embedded inline by dompdf, exactly as before.
      2. A PDF that has rasterised page previews (App\Support\ClaimPdfPreview, generated by
         pdf.js in the browser) -> those pages shown inline, so the row shows a picture
         instead of a sentence. The PDF is STILL appended in full by ClaimReportRenderer;
         these are a preview of the record, never a replacement for it, which is why the
         "reproduced in full on the pages after this form" note is kept beneath them.
      3. A PDF with no previews yet -> the original wording, unchanged. Previews are written
         when someone opens the claim, so a report downloaded before that must still read
         exactly as it always did rather than claim a picture is missing.

    Extracted from four near-identical copies. Blade's directive pattern uses \B, so an
    @endif glued to the end of a word compiles through as literal text (CLAUDE.md records
    three occurrences of this); keeping the markup in ONE place keeps that hazard in one
    place too. Every directive here follows a `}}`, a tag, or a line start.

    Expects from the parent scope: $imgData, $imageExt, $appendix.
    Takes: $path, $label ('Attachment'|'Supporting'), $maxHeight.
--}}
@php
    $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
    $data = in_array($ext, $imageExt) ? $imgData('local', $path) : null;

    $previews = [];
    if (! $data && \App\Support\ClaimPdfPreview::isPdf($path)) {
        foreach (\App\Support\ClaimPdfPreview::existing($path) as $previewPath) {
            if ($encoded = $imgData('local', $previewPath)) {
                $previews[] = $encoded;
            }
        }
    }

    $entry = $appendix[$path] ?? null;
    $note = ($entry && $entry['appendable'])
        ? ' — reproduced in full on the pages after this form'
        : (($entry && $entry['reason']) ? ' ('.$entry['reason'].')' : '');

    $shown = count($previews);
    $pageWord = $shown === 1 ? 'page' : 'pages';
@endphp
@if($data)
<img src="{{ $data }}" style="max-width:100%;max-height:{{ $maxHeight }}px;display:block;margin:3px 0;">
@elseif($shown > 0)
@foreach($previews as $preview)
<img src="{{ $preview }}" style="max-width:100%;max-height:{{ $maxHeight }}px;display:block;margin:3px 0;border:1px solid #e2e8f0;">
@endforeach
<div class="muted">{{ $label }}: PDF — {{ $shown }} {{ $pageWord }} shown above{{ $note }}.</div>
@else
<div class="muted">{{ $label }}: {{ strtoupper($ext) }} file (not embeddable in this PDF){{ $note }}.</div>
@endif
