<?php

namespace App\Http\Controllers;

use App\Models\Vendor;
use App\Models\VendorDocumentScan;
use App\Services\VendorDocumentInsightService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

/**
 * Read an uploaded vendor document BEFORE it is filed, so the operator reviews and corrects
 * the summary rather than discovering it afterwards on the row.
 *
 * This is a scan-before-save path, which the module deliberately did not have between
 * 2026-08-11 and 2026-08-13. What was removed then was a per-FIELD scan that pre-filled a
 * form full of inputs; what this does is read the document for its SUMMARY — the reading
 * the module kept — and hand back the record values as a by-product so nobody has to type
 * a date that is printed on the page. The old warning still holds and is honoured: the
 * fields do NOT ride along inside the transcription reply, they come from a second, small
 * call over the transcript (VendorDocumentInsightService::readDetails), so a long document
 * running past max_tokens costs the tail of the transcript and nothing else.
 *
 * SYNCHRONOUS on purpose, and hedged against its own worst case. The whole point is that
 * the summary is on screen before the record exists, which a queued job cannot deliver —
 * the queue here is drained by a once-a-minute scheduled worker. A long PDF can therefore
 * outlive the edge timeout on live, so the staging row is created BEFORE the model is
 * called and the browser sends a token with the upload: if the response is lost, the work
 * is still done, still paid for, and still reachable through `status`.
 */
class VendorDocumentScanController extends Controller
{
    private function authorizeManage(): void
    {
        if (! Auth::user()->canManageVendors()) {
            abort(403, 'No permission to manage vendors.');
        }
    }

    /**
     * Store an uploaded document, read it, and return what it says.
     *
     * Nothing is filed here. The vendor profile gains no row until the operator saves the
     * summary they have just been shown.
     */
    public function scan(Request $request, Vendor $vendor)
    {
        $this->authorizeManage();

        $data = $request->validate([
            'kind' => ['required', 'string', Rule::in(array_keys(VendorDocumentScan::DIRECTORIES))],
            // Generated by the browser. Bounded and character-restricted because it is
            // stored and later matched on: a token is a lookup key, never free text.
            'token' => ['required', 'string', 'min:8', 'max:64', 'regex:/^[A-Za-z0-9\-]+$/'],
            'document' => 'required|file|mimes:pdf,jpg,jpeg,png|max:10240|valid_file_content',
        ]);

        // Re-picking a file in the same modal reuses the token. Discard the previous
        // attempt WITH its file — otherwise every changed mind leaks an upload that the
        // nightly sweep has to find later.
        $this->existingScan($vendor, $data['token'])?->discard();

        $file = $request->file('document');
        $path = $file->store(VendorDocumentScan::directoryFor($data['kind'], $vendor->id), 'local');

        // Written BEFORE the model is called. This row is what makes a lost response
        // recoverable, so it has to exist while the call that fills it is still running.
        $scan = VendorDocumentScan::create([
            'vendor_id' => $vendor->id,
            'user_id' => Auth::id(),
            'token' => $data['token'],
            'kind' => $data['kind'],
            'file_path' => $path,
            'original_filename' => mb_substr((string) $file->getClientOriginalName(), 0, 255),
            'status' => 'pending',
        ]);

        $this->read($scan, $vendor);

        return response()->json($scan->fresh()->toModalPayload());
    }

    /**
     * What a scan produced, for a client that lost the scan response.
     *
     * The read runs inside the upload request, so a document that takes longer than the
     * edge will allow returns a gateway error to the browser while PHP finishes normally.
     * Polling here is how that work is collected instead of being paid for twice.
     */
    public function status(Request $request, Vendor $vendor)
    {
        $this->authorizeManage();

        $token = $request->validate([
            'token' => ['required', 'string', 'min:8', 'max:64', 'regex:/^[A-Za-z0-9\-]+$/'],
        ])['token'];

        $scan = $this->existingScan($vendor, $token);

        if (! $scan) {
            return response()->json(['error' => 'That upload is no longer available. Please attach the document again.'], 404);
        }

        return response()->json($scan->toModalPayload());
    }

    // ── Internals ─────────────────────────────────────────────────────────────

    /**
     * This operator's unfinished upload under this token, for this vendor.
     *
     * Scoped by all three. The vendor id comes from the URL and the token from the request,
     * so without the vendor check a token could reach a file uploaded against a different
     * vendor; without the user check, a guessed token would hand somebody another person's
     * upload — and the summary of a document they were never shown.
     */
    private function existingScan(Vendor $vendor, string $token): ?VendorDocumentScan
    {
        return VendorDocumentScan::where('vendor_id', $vendor->id)
            ->where('user_id', Auth::id())
            ->where('token', $token)
            ->first();
    }

    /**
     * Read the stored file into the staging row.
     *
     * FAILS OPEN, like every AI path here: a provider outage lands as `failed` on the row
     * and the modal offers an empty summary box with the reason stated. The document is
     * already on disk and can still be filed — an unreadable file must never be an
     * unfileable one.
     */
    private function read(VendorDocumentScan $scan, Vendor $vendor): void
    {
        try {
            $disk = Storage::disk('local');

            $result = VendorDocumentInsightService::readDetails(
                $disk->path($scan->file_path),
                (string) $disk->mimeType($scan->file_path),
                // The staging kinds map 1:1 onto the reader's kinds. 'billing' rather than a
                // guess between quotation and invoice: the form no longer asks, so the
                // reading is what decides which of the two it is.
                $scan->kind,
                $vendor->name
            );

            $scan->update([
                'status' => $result['status'],
                'summary' => $result['summary'],
                'key_points' => $result['key_points'] ?: null,
                'text' => $result['text'],
                'companies' => ($result['companies'] ?? []) ?: null,
                'fields' => ($result['fields'] ?? []) ?: null,
            ]);
        } catch (\Throwable $e) {
            $scan->update(['status' => 'failed']);

            Log::warning('Vendor document scan failed', [
                'scan' => $scan->id,
                'vendor' => $vendor->id,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
